name: Deploy to Oracle Cloud

on:
    push:
        branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    # ESSA É A LINHA QUE ESTÁ FALTANDO:
    # Substitua 'NOME_DO_SEU_AMBIENTE' pelo nome exato que está no GitHub Settings
    environment: oracle

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3 # Recomendo usar v1.0.3 para estabilidade
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_SSH_KEY }}
          port: 22
          script: |
            cd ~/advec-automation
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker image prune -f
